version: '3.4'

services:
  carlaACCsimulation:
    image: carlaACCsimulation
    build:
      context: .
      dockerfile: ./Dockerfile

  dev:
    image: simulation_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 127.0.0.1:9922:22
    volumes:
      - .:/code/
    environment:
      DEV: 'True'
        #    env_file: local.env
